name: FlutterCI #CI名称
on: [push] #触发条件push操作！
    
jobs:
  check:
    name: Test on ${{ matrix.os }}
    #运行在哪个平台这里是MacOS平台
    runs-on: macOS-11
    
    steps:
      - uses: actions/checkout@v1
      #三方flutter的Action，它可以在服务器配置一个Flutter环境
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.5.3'
          channel: 'stable'
      #想让我们CI做的事情！
      - run: flutter doctor -v
      - run: cd my_flutter_module && flutter build ios-framework --output=../NativeAPP/Flutter
      - run: git config --global http.postBuffer 524288000 
      - run: |
         git add .
         git commit -m 'update flutter framework' 
     
      - name: Push changes
        #选择分支master
        uses: ad-m/github-push-action@master 
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
